"""Domain concepts and errors."""

from .errors import WorkoutDefinitionError
from .models import Program, Step, Week, Workout
from .pace import (
    FIVE_KM,
    HALF_MARATHON_KM,
    KM_PER_MILE,
    MARATHON_KM,
    ONE_KM,
    PACE_INTENSITIES,
    RECOVERY_OFFSET_SECONDS_PER_KM,
    RIEGEL_EXPONENT,
    TEMPO_OFFSET_SECONDS_PER_KM,
    TEN_KM,
    TRAINING_INTENSITY_OFFSETS,
    five_k_pace_seconds,
    format_pace_seconds,
    intensity_pace_seconds,
    one_k_pace_to_five_k_seconds,
    pace_zone,
    parse_total_seconds,
    race_pace_seconds,
    round5,
    total_from_pace,
)
from .selectors import WeekSelection, WeekSelectionError
from .workout_form import (
    EASY_RUN,
    FORM_BY_NAME,
    INTERVAL_WORKOUT,
    LONG_RUN,
    RECOVERY_RUN,
    RUN_WALK,
    TEMPO_RUN,
    WorkoutForm,
    WorkoutFormName,
    WorkoutWithForm,
    infer_workout_form,
)

__all__ = [
    "EASY_RUN",
    "FIVE_KM",
    "FORM_BY_NAME",
    "HALF_MARATHON_KM",
    "INTERVAL_WORKOUT",
    "KM_PER_MILE",
    "LONG_RUN",
    "MARATHON_KM",
    "ONE_KM",
    "PACE_INTENSITIES",
    "Program",
    "RECOVERY_OFFSET_SECONDS_PER_KM",
    "RECOVERY_RUN",
    "RIEGEL_EXPONENT",
    "RUN_WALK",
    "Step",
    "TEMPO_OFFSET_SECONDS_PER_KM",
    "TEMPO_RUN",
    "TEN_KM",
    "TRAINING_INTENSITY_OFFSETS",
    "Week",
    "WeekSelection",
    "WeekSelectionError",
    "Workout",
    "WorkoutDefinitionError",
    "WorkoutForm",
    "WorkoutFormName",
    "WorkoutWithForm",
    "five_k_pace_seconds",
    "format_pace_seconds",
    "infer_workout_form",
    "intensity_pace_seconds",
    "one_k_pace_to_five_k_seconds",
    "pace_zone",
    "parse_total_seconds",
    "race_pace_seconds",
    "round5",
    "total_from_pace",
]
