"""Domain concepts and errors."""

from .errors import WorkoutDefinitionError
from .models import Program, Step, Week, Workout
from .pace import (
    FIVE_KM,
    HALF_MARATHON_KM,
    KM_PER_MILE,
    MARATHON_KM,
    ONE_KM,
    PACE_INTENSITIES,
    RECOVERY_OFFSET_SECONDS_PER_KM,
    RIEGEL_EXPONENT,
    TEMPO_OFFSET_SECONDS_PER_KM,
    TEN_KM,
    TRAINING_INTENSITY_OFFSETS,
    five_k_pace_seconds,
    format_pace_seconds,
    intensity_pace_seconds,
    one_k_pace_to_five_k_seconds,
    pace_zone,
    parse_total_seconds,
    race_pace_seconds,
    round5,
    total_from_pace,
)
from .selectors import WeekSelection, WeekSelectionError

__all__ = [
    "FIVE_KM",
    "HALF_MARATHON_KM",
    "KM_PER_MILE",
    "MARATHON_KM",
    "ONE_KM",
    "PACE_INTENSITIES",
    "Program",
    "RECOVERY_OFFSET_SECONDS_PER_KM",
    "RIEGEL_EXPONENT",
    "Step",
    "TEN_KM",
    "TEMPO_OFFSET_SECONDS_PER_KM",
    "TRAINING_INTENSITY_OFFSETS",
    "Week",
    "WeekSelection",
    "WeekSelectionError",
    "Workout",
    "WorkoutDefinitionError",
    "five_k_pace_seconds",
    "format_pace_seconds",
    "intensity_pace_seconds",
    "one_k_pace_to_five_k_seconds",
    "pace_zone",
    "parse_total_seconds",
    "race_pace_seconds",
    "round5",
    "total_from_pace",
]
